version: '2'
services:
  bot:
    build: .
    container_name: 'ovisbot'
    restart: always
    volumes:
      - .:/ovisbot
    working_dir: /ovisbot
    command: bash -c "pip install . && ovisbot"
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    restart: always
    volumes:
      - db-data:/data/db
volumes:
  db-data:
    driver: local
